const timeLeft = document.querySelector(".time-left")
const result = document.querySelector(".result")
const btn = document.querySelector(".start-pause-button")
const grid = document.querySelector(".grid")
const squares = document.querySelectorAll(".grid div")